### ISSUE TITLE
Please remove from Github

### ISSUE THREAD

**Issue by joel-porquet** [schen510/ECS150-Projects#1]
Hi,
I'm contacting you because I'm the current instructor for ECS150 at UC Davis. The project that I'm giving to students this quarter is very related to this one and in order to avoid any potential cheating, it would be very considerate of you to please remove this code from Github or switch it to a private repository.
Thank you for your understanding,
Dr Joël Porquet

**Comment by schen5** [comment]
Hi Joel,

That's fine; I understand. Is it just for this quarter or will it be long term?

**Comment by joel-porquet** [comment]
Thanks for your quick answer.
My class will be taught the next two quarters, as well as probably next year, so it's long term.

**Comment by schen5** [comment]
Okay that's fine. However, I would like to use these projects as references on my github in the future if I'm looking for a job, since they covered a lot of interesting topics(threading, schedulers, etc.). I hope that will be okay. I will let you know if I choose to use it and at that point, we can discuss further possible compromises?

Thanks for understanding!

**Comment by joel-porquet** [comment]
Sounds good. Thanks.
